os: osx
osx_image: xcode13.2
language: swift
script: xcodebuild clean build test -project FoodFest.xcodeproj -scheme "FoodFest" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.2,name=iPhone 11 Pro" ONLY_ACTIVE_ARCH=NO